name: adaptive-detection
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.6.4
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.12.9
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - ezdxf==1.4.0
      - fonttools==4.56.0
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - numpy==2.2.4
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pillow==11.1.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - scipy==1.15.2
      - shapely==2.0.7
      - six==1.17.0
      - sv-ttk==2.6.0
      - typing-extensions==4.13.0